### ISSUE TITLE
Amazing results! 

### ISSUE THREAD

**Issue by RomaKoks** [teticio/Deej-AI#31]
Quality of generated playlists is really great, thank you for your work!
Along the way, it allows to deduplicate the music library, since the same tracks follow each other)) I've been dreaming of doing something like this for a very long time! 
Do you consider downloading texts and searching for the nearest ones not only by spectrogram, but also by "meaning" as the development of the project? Perhaps a linear combination of similarity in music and text...This could allow you to search for at least tracks in one language)

**Comment by teticio** [comment]
Hi!

Thanks for your feedback! So, for example downloading lyrics and taking them into account? You could certainly do something like that. I suppose I am more into instrumental music so I haven't thought of doing it :-). I think there are many ways to improve it. I since downloaded the million playlist dataset from Spotify which was not available at the time I did this project (or I was not aware of it when it was). Also, I think "triplet loss" could be a good way to teach the model to discriminate more. It would also be great to build a pipeline that keeps updating it based on new music. As it stands, the music catalogue it has is from October 2018.

I am currently interested in generative models and there I think the combination of text + music could be really powerful. So, like DALL-E 2, train with music + descriptions (there are websites with royalty free music that have detailed descriptions).

Exciting times!
